# FTSE Market Summary & Portfolio Analysis

KATE expects your code to define variables with specific names that correspond to certain things we are interested in.

KATE will run your notebook from top to bottom and check the latest value of those variables, so make sure you don't overwrite them.

* Remember to uncomment the line assigning the variable to your answer and don't change the variable or function names.
* Use copies of the original or previous DataFrames to make sure you do not overwrite them by mistake.

You will find instructions below about how to define each variable.

Once you're happy with your code, upload your notebook to KATE to check your feedback.

In [6]:
import pandas as pd
import numpy as np

First, take a look at the dataset called `FTSE100.csv` (consider using the `.read_csv`, `.head`, and `.info` methods) in a notebook. This dataset is provided in the zip with this project.

In [7]:
df = pd.read_csv('data/FTSE100.csv')
df.head()

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Strong Buy,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,"1,099.50",0.0171,Hold,5,NaN,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,"2,115.00",-0.42%,Hold,18,NaN,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,"1,744.00",0.0154,Hold,24,NaN,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,NaN,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,"2,207.00",0.0347,Buy,17,NaN,12,5,0,0,Buy

In [8]:
#df.describe
#df.columns
#df.index
df.shape

(101, 13)

In [9]:
df.dtypes

Company            object
Ticker             object
Sector             object
Mid-price (p)      object
Change             object
Our view           object
Brokers             int64
Strong Buy        float64
Buy                 int64
Neutral             int64
Sell                int64
Strong Sell         int64
Recommendation     object
dtype: object

## 1. Tidy Data


The dataset has a column with only `n/a` values, and also 101 rows (you may have been expecting 100!). This is because one of the companies (Royal Dutch Shell) has two entries. We can get rid of the first instance of these (RDSA).

Starting from a copy of `df`, create a new dataFrame called `clean_df` with the following changes:
- Drop the row with a `Ticker` value of `RDSA`
- Drop the `Strong Buy` column

In [10]:
# Add your code here
clean_df = df.copy()
# Make sure you call your new dataframe clean_df
clean_df = clean_df[clean_df['Ticker']!='RDSA'].drop(columns=["Strong Buy"])

## 2. Change Column Data Type

Look at the values in the `Mid-price (p)` column. At first glance they may look like floats but in fact they have been interpreted as text. We need to change them to floats for them to be more useful.

Starting from a copy of `clean_df`, create a new DataFrame called  `price_df` with the following change:

- Convert the values in the `Mid-price (p)` column to floats (keeping the column in the same place)

*Hint: converting directly to a float may not work if there are commas in the strings; you may find the [str.replace](https://docs.python.org/3/library/stdtypes.html#str.replace) method useful for fixing this before conversion.*

In [11]:
# Add your code here
price_df = clean_df.copy()
# Make sure you call your new dataframe price_df
price_df['Mid-price (p)'] = price_df['Mid-price (p)'].str.replace(',','').astype(float)
price_df.head(5)

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,1099.5,0.0171,Hold,5,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,2115.0,-0.42%,Hold,18,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,1744.0,0.0154,Hold,24,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,2207.0,0.0347,Buy,17,12,5,0,0,Buy

In [12]:
price_df.dtypes

Company            object
Ticker             object
Sector             object
Mid-price (p)     float64
Change             object
Our view           object
Brokers             int64
Buy                 int64
Neutral             int64
Sell                int64
Strong Sell         int64
Recommendation     object
dtype: object

## 3. Format Change Values

Take a look at the values in the `Change` column. You'll see that they are in an inconsistent format, and stored as strings. The positive values need to be multiplied by 100. The negative values need to have the `%` sign removed.

**Part 1:** Create a function called `format_change` which takes a string such as those in the Change column and does the following:
1. if the last character is a % sign, remove it 
2. convert the string to a float
3. if that float is posiive, multiply it by 100
4. return the resulting float

In [13]:
# Add your code below
def format_change(change):
    change = change.strip('%') 
    
    to_float = float(change)
    
    if to_float > 0:
        to_float = to_float * 100
        
    return to_float

You can check that your function works as expected below:

In [14]:
# Uncomment the code below to test your function
format_change('0.45%')

45.0

**Part 2:** Starting from a copy of `price_df`, create a new DataFrame called  `change_df` with a new column called `Change (%)`:

- This should contain the result returned from the function created above when given the original `Change` column value as the argument.

In [15]:
change_df = price_df.copy()

In [16]:
change_df['Change (%)'] = change_df['Change'].apply(format_change)

In [17]:
change_df.head(5)

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation,Change (%)
0,3i,III,Financial Services,1099.5,0.0171,Hold,5,4,1,0,0,Buy,1.71
1,Admiral Group,ADM,Nonlife Insurance,2115.0,-0.42%,Hold,18,2,6,7,3,Underweight,-0.42
2,Anglo American plc,AAL,Mining,1744.0,0.0154,Hold,24,15,6,2,0,Buy,1.54
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,8,9,3,0,Overweight,3.26
4,Ashtead Group,AHT,Support Services,2207.0,0.0347,Buy,17,12,5,0,0,Buy,3.47

## 4. Holding Summary

We are given the details of a share holding in a tuple, containing the company ticker code, number of shares, and price paid, defined below:

In [18]:
holding = ('BP.', 500, 1535.21)

Starting from the `holding` above and `change_df`, build a new dictionary containing the following keys and the appropriate values in the given data formats.

```
{    
    holding_cost: float,    
    # The cost (in £, not pence) of the holding (number of shares * price paid)
    holding_value: float,    
    # The value (in £, not pence) of the holding (number of shares * current mid-price) 
    change_in_value: float,    
    # The percentage change from the original cost of the holding to the current value  
    (e.g. if the holding_value is 1.2 * the holding_cost, the change_in_value should equal 20.0)
    
}
```

Call this dictionary `holding_dict`

In [19]:
holding_cost = float((holding[1]*holding[2])/100)
holding_value = float((holding[1]*float(change_df.query("Ticker =='BP.'")["Mid-price (p)"]))/100)
change_in_value = round(((holding_value - holding_cost)/holding_cost)*100, 1)
holding_names = ["holding_cost", "holding_value", "change_in_value"]
holding_list = [holding_cost, holding_value, change_in_value]
holding_dict = dict(zip(holding_names, holding_list))

print(holding_dict)

{'holding_cost': 7676.05, 'holding_value': 8665.0, 'change_in_value': 12.9}

## 5. Market Comparison

Provided with the DataFrame you processed above, `change_df`, we would like to compare the % change in the mid-price for each company to the average % change for all companies in the market, along with a summary of the broker recommendations.

Create a DataFrame called `comparison_df` with the following columns added to a copy of `change_df`: 

- 'Beat Market'    # This should be a Boolean column with `True` for stocks where `Change (%)` exceeds that of the average market change
- 'Buy Ratio'    # This should equal the `Buy` column divided by the `Brokers` column.

*Hint: Calculate the average market change % first then compare each value in the Change (%) column to that when creating the new column.*

In [20]:
change_df['Change (%)'].mean()

0.7033

In [21]:
# Add your code here
# Make sure you call your new dataframe comparison_df
comparison_df = change_df.copy()
comparison_df['Beat Market'] = np.where(comparison_df['Change (%)'] > 0.7033, True, False)

In [22]:
comparison_df['Buy Ratio'] = comparison_df['Buy'] / comparison_df['Brokers']

In [37]:
comparison_df.head(20)

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation,Change (%),Beat Market,Buy Ratio
0,3i,III,Financial Services,1099.50,0.0171,Hold,5,4,1,0,0,Buy,1.71,True,0.800000
1,Admiral Group,ADM,Nonlife Insurance,2115.00,-0.42%,Hold,18,2,6,7,3,Underweight,-0.42,False,0.111111
2,Anglo American plc,AAL,Mining,1744.00,0.0154,Hold,24,15,6,2,0,Buy,1.54,True,0.625000
3,Antofagasta,ANTO,Mining,848.20,0.0326,Hold,21,8,9,3,0,Overweight,3.26,True,0.380952
4,Ashtead Group,AHT,Support Services,2207.00,0.0347,Buy,17,12,5,0,0,Buy,3.47,True,0.705882
5,Associated British Foods,ABF,Food Producers,2260.00,0.00,Hold,20,13,5,1,0,Buy,0.00,False,0.650000
6,AstraZeneca,AZN,Pharmaceuticals & Biotechnology,7368.00,0.014,Buy,25,16,5,2,2,Buy,1.40,True,0.640000
7,Auto Trader Group,AUTO,Media,523.80,-0.42%,Hold,19,4,11,4,0,Neutral,-0.42,False,0.210526
8,Aveva,AVV,Software & Computer Services,3698.00,-0.38%,Hold,15,5,7,2,0,Overweight,-0.38,False,0.333333
9,Aviva,AV.,Life Insurance,356.40,0.0082,Buy,17,12,4,0,0,Buy,0.82,True,0.705882
10,BAE Systems,BA.,Aerospace & Defence,544.20,0.0138,Buy,19,9,10,0,0,Overweight,1.38,True,0.473684
11,Barclays,BARC,Banks,137.58,0.0104,Hold,18,8,6,2,0,Overweight,1.04,True,0.444444
12,Barratt Developments,BDEV,Household Goods & Home Construction,629.00,0.0064,Hold,13,7,3,2,0,Overweight,0.64,False,0.538462
13,Berkeley Group Holdings,BKG,Household Goods & Home Construction,2870.50,0.0143,Hold,12,3,5,3,0,Neutral,1.43,True,0.250000
14,BHP,BHP,Mining,3865.00,0.0238,Hold,23,3,16,2,2,Neutral,2.38,True,0.130435
15,BP,BP.,Oil & Gas Producers,1733.00,0.0123,Buy,29,15,9,0,1,Buy,1.23,True,0.517241
16,British American Tobacco,BATS,Tobacco,503.30,0.0091,Buy,20,14,4,1,1,Buy,0.91,True,0.700000
17,British Land,BLND,Real Estate Investment Trusts,509.60,-0.04%,Hold,15,1,11,2,0,Neutral,-0.04,False,0.066667
18,BT Group,BT-A,Fixed Line Telecommunications,163.88,0.0079,Hold,19,11,6,2,0,Overweight,0.79,True,0.578947
19,Bunzl,BNZL,Support Services,1990.50,0.0061,Buy,14,5,3,5,0,Neutral,0.61,False,0.357143

## 6. Investigate

We want to identify any companies which match a given set of rules, so that we can look into them further.   

We want to identify companies in `watchlist` that meet at least one of the following requirements:

i) Any company in `watchlist` whose prices is equal to or lower than the given target price.

ii) Any company in `watchlist` where `Buy Ratio` is 0.5 or greater.

Using the `watchlist` below and `comparison_df` you defined, create a list of companies meeting the requirements, call this list `companies_list`. The list should only have the company names, not the price.

Note: **A company meeting both requirements should only appear once in the list**.

*Hint: create an empty list to add company names to, using a loop to work through the watchlist. If you want to get the first item in a series of values (such as a column of a filtered dataframe), you can use* `.values[0]` *on the column.*

In [24]:
watchlist = [('TUI', 820.0), ('Whitbread', 4300.0), ('AstraZeneca', 7500.0), 
             ('Standard Chartered', 920.0), ('Barclays', 135.5)]

In [32]:
# Add your code here
# Make sure you call your new list companies_list
companies_list = []

for item in watchlist:
    cond1 = comparison_df[comparison_df['Company'] == item[0]]['Mid-price (p)'].values[0] <= item[1]
    cond2 = comparison_df[comparison_df['Company'] == item[0]]['Buy Ratio'].values[0] >= 0.5
    if cond1 or cond2:
        companies_list.append(item[0])

In [33]:
companies_list

['TUI', 'AstraZeneca', 'Standard Chartered']